name: Build and Deploy React App to AWS EKS

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: us-east-1
      ECR_REPOSITORY: demoapp
      EKS_CLUSTER_NAME: my-eks-cluster

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # Step 1: Build React app
    - name: Install dependencies and build React app
      working-directory: my-react-app
      run: |
        npm install
        CI=false npm run build

    # Step 2: Configure AWS credentials
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    # Step 3: Login to ECR
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    # Step 4: Build and Push Docker image
    - name: Build and Push Docker image
      working-directory: ReactApp
      run: |
        IMAGE_TAG=${{ github.run_number }}
        IMAGE_URI=${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${IMAGE_TAG}
        docker build -t $IMAGE_URI .
        docker push $IMAGE_URI
        echo "IMAGE_URI=$IMAGE_URI" >> $GITHUB_ENV

    # Step 5: Update kubeconfig for EKS
    - name: Update kubeconfig for EKS
      run: |
        aws eks update-kubeconfig --region ${{ env.AWS_REGION }} --name ${{ env.EKS_CLUSTER_NAME }}

    # Step 6: Deploy to EKS
    - name: Deploy to EKS
      run: |
        kubectl apply -f k8s/deployment.yml
        kubectl apply -f k8s/service.yml
        kubectl set image deployment/demoapp-deployment demoapp-container=${{ env.IMAGE_URI }}
